### PR TITLE
Added package install service

### LINKED ISSUE #7: Design of the package installer service
There is the packages section in the yaml config as follows:

```yaml
packages:
  directory: "/mnt/directory-with-rpm-files"
  directory: "/mnt/another-directory-with-rpm-files"
```

I'd like to start a discussion on how those packages should become installed

Basically there are two options:

1. Take all packages from the listed directories and install them the brute force way by calling ```rpm```

2. Create a clean repository from the packages using the ```createrepo``` tool, register that repo to the zypper packagemanager and install all packages in a transaction with the ```zypper``` tool

I vote to do it "right" with option 2. That's because of the following reasons:

* A package install transaction through zypper checks for consistency and dependencies and allows to resolve all package dependencies in a clean way. Of course there is also potential that this fails resulting in the package to be not installable

* A package installation via zypper takes all other configured repositories into account and helps to keep the system integrity intact

* A package installation via zypper provides good error messages in terms of problems with dependencies, conflicts and others

The brute force way ignores all that and brain dead installs data on the machine which I personally would not do. If there are no objections I'll implement option 2.

Thoughts ?

### PR DESCRIPTION
**Pull request by schaefi**
Allow to install packages from local repository
This Fixes #7

### CODE REVIEW

**Comment by schaefi** [comment]
First shot for a package installer service. The yaml file has changed to the following form:

```yaml
packages:
  repository_name: azure_packages
  directory:
    - "/directory-with-rpm-files"
    - "/another-directory-with-rpm-files"
```

**Comment by schaefi** [comment]
During implementation I was thinking about that we do not specify which packages should become installed. Thus the assumption is that all packages from all given directories are expected to become installed.

**Comment by jeffaco** [comment]
> During implementation I was thinking about that we do not specify which packages should become
> installed. Thus the assumption is that all packages from all given directories are expected to become
> installed.

I thought about that as well. Given that the LUN (or DVD) is temporary, I think it's fine that we just will put packages we want installed on the LUN. If we don't want a package installed, it shouldn't be on the LUN and the directory shouldn't mentioned in the YAML file.

**Comment by jeffaco** [comment]
```
packages:
  repository_name: azure_packages
```

Added to [gist](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a)

**Comment by schaefi** [comment]
@jeffaco thanks for the feedback, so we are all on the same page regarding what packages gets installed. I'll merge this next

> I wonder if the YAML would be better as a repo, where pull requests can be made?

I maintain two versions one for li and one for vli (currently the same content) as part of the tests here:

* https://github.com/SUSE/azure-li-services/tree/master/test/data

There contents are relevant for the unit tests to pass and thus relevant for the code we write here. I think you can point people there. However please note if you do changes to that files without having made the needed code changes the tests will fail and that will be reported and prevents releases by intention.

I think if you need a place to reference a file with new suggestions, the gist is a good place. If you need a place to reference a file and be sure that's the one in line with the current implementation, the repo source is the best place.

Personally I prefer to have only one place telling the truth, which is the repo source. Suggestions or discussions for updates/changes we do great in issues on github and so I did not had the need to look at the gist for a while. 

Does this makes sense ?

**Comment by jeffaco** [comment]
Makes perfect sense, thanks. Let me know when you have a new image for me to test, and exactly what new features are in it, thanks!

**Pull request merged**
