### PR TITLE
Added overall state reporting service

### LINKED ISSUE #19: Error handling on service failure
__Description__

In the scope of the azure li services there is potential that something fails or does not match the machine requirements. In this case a procedure to inform the user and the ability to access the system is desired.

### PR DESCRIPTION
**Pull request by schaefi**
Added check for success state from all services and update
the /etc/issue file if one or more services have a failed
state. This completes and Fixes #19

### CODE REVIEW

**Comment by schaefi** [comment]
All right this implements the /etc/issue setup as we have discussed it. Along with writing the code I also verified that the uninstall of the azure-li-services package does not wipe the status information of the services when they got called by systemd.

Thus you can at any point in time retrieve the detailed service call information via

```
systemctl status ...
```

If you call e.g ```systemctl status user``` you get all data our user service provided at call time. You will also receive a warning from systemd that the file has changed on disk which is normal because the cleanup service has deleted it. We have to live with this warning until one calls a ```systemd daemon reload``` However please note, once you reload the systemd daemon the cached log information from no longer present service will be deleted.

**Comment by schaefi** [comment]
You probably want to have a close look on the contents of /etc/issue. Please let me know if this text fits your needs. Well it could be changed at any later point in time too but if we for example already know some contact person or list we better add it right from the beginning on.

Thanks

**Comment by rjschwei** [comment]
Looking at this it makes me wonder if we should not separate clean-up and reporting. I am thinking that the addition of the reporting convoluted the straight forward removal of the package. Having a separate "-report-failure" service that gets activated by any of the other units with the "OnFailure" setting might provide a nicer separation of duties. By default "/etc/issues" would simply contain "SUCCESS", this we can put in config.sh or the overlay tree. Then when any unit fails the "-report-failure" unit is activated which will basically be the code you have now, just separated out.

There is nothing I see that needs to change in this implementation I just think we would be better off to not intermingle reporting and clean up.

**Comment by rjschwei** [comment]
I would only run the reporting service "OnFailure" of any of the other services, but it is small enough an can run all the time, as currently implemented, certainly a valid choice.

**Pull request merged**
